global:
  scrape_interval: 15s
  scrape_timeout: 10s

scrape_configs:
  - job_name: techchallenge
    metrics_path: /metrics
    static_configs:
      - targets:
          - api:8080

  - job_name: prometheus
    metrics_path: /metrics
    static_configs:
      - targets:
          - 0.0.0.0:9090

  - job_name: docker
    metrics_path: /metrics
    static_configs:
      - targets:
          - host.docker.internal:9323